query getGlobalSettings {
    bruteForceLoginProtection {
        globalSettings {
            activated
            whitelistIps
            ignorePatterns
            ignorePaths
            trustProxyHeader
            emailEnabled
            emailRecipient
            webhookUrl
            webhookSecretConfigured
            auditLogMaxEntries
            recidiveFactor
            maxBanTimeSeconds
            blocklistIps
            torBlocklistEnabled
            torBlocklistUrl
            torBlocklistRefreshSeconds
        }
    }
}
